# This file extends the docker-compose.yml with production configurations/overrides. https://docs.docker.com/compose/compose-file/13-merge/
version: "3.8"
services:
  vaultwarden:
    # Add a name to easy identify
    container_name: vaultwardenProd

    # Configurations: https://github.com/dani-garcia/vaultwarden/blob/main/.env.template
    environment:
      # The domain must match the address from where you access the server
      DOMAIN: https://${HOST?Missing environment variable see readme}
      # Reverse proxy config. See: https://github.com/Good-Games-Munich/nginx
      VIRTUAL_HOST: ${HOST?Missing environment variable see readme}
      VIRTUAL_PORT: 80 # Port of service to procy inside container
      LETSENCRYPT_HOST: ${HOST:?Missing environment variable see readme}

    # Reverse proxy network. See: https://github.com/Good-Games-Munich/nginx
    networks:
      - default
      - nginxproxynet

# Reverse proxy network. See: https://github.com/Good-Games-Munich/nginx
networks:
  nginxproxynet:
    name: nginxproxynet
    external: true
